[project]
name = "detr"
version = "0.0.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["detr", "detr.d2", "detr.d2.detr", "detr.datasets", "detr.models", "detr.util"]
